// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBec1bOcmg-e5E5_DHnbXyDMBC8gbTyplw',
    appId: '1:928735450976:web:6aa9ed334011b8ea323005',
    messagingSenderId: '928735450976',
    projectId: 'flowers-project-f0d17',
    authDomain: 'flowers-project-f0d17.firebaseapp.com',
    storageBucket: 'flowers-project-f0d17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALZ8nSBOxLeS_YQKoYvmIwO05y36y8LXw',
    appId: '1:928735450976:android:ad187c65828de34c323005',
    messagingSenderId: '928735450976',
    projectId: 'flowers-project-f0d17',
    storageBucket: 'flowers-project-f0d17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4V3D_lLVIV30spfz8sRZGgnl1uccQdSg',
    appId: '1:928735450976:ios:14e8b50cb51f79a0323005',
    messagingSenderId: '928735450976',
    projectId: 'flowers-project-f0d17',
    storageBucket: 'flowers-project-f0d17.appspot.com',
    iosBundleId: 'com.example.flowers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4V3D_lLVIV30spfz8sRZGgnl1uccQdSg',
    appId: '1:928735450976:ios:14e8b50cb51f79a0323005',
    messagingSenderId: '928735450976',
    projectId: 'flowers-project-f0d17',
    storageBucket: 'flowers-project-f0d17.appspot.com',
    iosBundleId: 'com.example.flowers',
  );
}
